# Build
FROM node:18-alpine AS builder
WORKDIR /app

COPY . ./
COPY package*.json ./

RUN npm ci \
    && npm run build

# Release
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/package.json /app/
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/dist /app/dist

RUN addgroup -S appuser && adduser -S appuser -G appuser \
    && chown -R appuser:appuser /app/ \
    && chmod 777 /app/

USER appuser

EXPOSE 3000

CMD ["npm", "run", "dev"]

